-- ==========================================
-- PROFILES
-- ==========================================
-- ==========================================
-- DELETE OLD TABLES
-- ==========================================
drop table if exists public.wishlist cascade;

drop table if exists public.products cascade;

drop table if exists public.profiles cascade;

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  first_name text not null,
  last_name text not null,
  email text not null,
  mobile text,
  student_id text unique,
  course text,
  created_at timestamptz default now()
);

-- ==========================================
-- PRODUCTS
-- ==========================================
create table public.products (
  id bigint generated by default as identity primary key,
  seller_id uuid references public.profiles (id) on delete cascade,
  name text not null,
  category text not null,
  condition text not null,
  price numeric(10, 2) not null check (price > 0),
  contact text not null,
  email text not null,
  location text not null,
  description text not null,
  image_url text,
  created_at timestamptz default now()
);

-- ==========================================
-- WISHLIST
-- ==========================================
create table public.wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles (id) on delete cascade,
  product_id bigint references public.products (id) on delete cascade,
  created_at timestamptz default now(),
  unique (user_id, product_id)
);

alter table public.profiles enable row level security;

alter table public.products enable row level security;

alter table public.wishlist enable row level security;

-- ==========================================
-- PROFILES POLICIES
-- ==========================================
create policy "Users can view their own profile" on public.profiles for
select
  to authenticated using (auth.uid () = id);

create policy "Users can create their own profile" on public.profiles for insert to authenticated
with
  check (auth.uid () = id);

create policy "Users can update their own profile" on public.profiles
for update
  to authenticated using (auth.uid () = id);

-- ==========================================
-- PRODUCTS POLICIES
-- ==========================================
create policy "Anyone can view products" on public.products for
select
  to anon,
  authenticated using (true);

create policy "Users can create products" on public.products for insert to authenticated
with
  check (auth.uid () = seller_id);

create policy "Users can update their products" on public.products
for update
  to authenticated using (auth.uid () = seller_id);

create policy "Users can delete their products" on public.products for delete to authenticated using (auth.uid () = seller_id);

-- ==========================================
-- WISHLIST POLICIES
-- ==========================================
create policy "Users can view their wishlist" on public.wishlist for
select
  to authenticated using (auth.uid () = user_id);

create policy "Users can add wishlist items" on public.wishlist for insert to authenticated
with
  check (auth.uid () = user_id);

create policy "Users can remove wishlist items" on public.wishlist for delete to authenticated using (auth.uid () = user_id);

select
  *
from
  public.profiles;

select
  *
from
  public.products;

select
  *
from
  public.wishlist;